console.log('Conquistador initialized');
window.releaseFunds = async (id) => {\n  const { releaseFundsOnChain } = await import('./ContractInteractions.js');\n    await releaseFundsOnChain(id);
  import('./Notifications.js').then(({ showNotification }) => showNotification('Funds Released!', 'success'));\n};
window.raiseDispute = async (id) => {\n  const { raiseDisputeOnChain } = await import('./ContractInteractions.js');\n    await raiseDisputeOnChain(id);
  import('./Notifications.js').then(({ showNotification }) => showNotification('Dispute Raised!', 'warning'));\n};
import { renderNav } from './Navigation.js';
document.getElementById('root').prepend(renderNav());
import { fetchTransactionHistory } from './TransactionHistoryService.js';
fetchTransactionHistory().then(txs => updateTransactionList(txs));
import { fetchReputationScore } from './ReputationService.js';
import { updateReputationCard } from './ReputationCard.js';
fetchReputationScore('ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM').then(data => updateReputationCard(data.score, data.total));
import { renderTxForm } from './TransactionForm.js';
document.getElementById('root').appendChild(renderTxForm());
